import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar"
import AppSidebar from "@/components/common/app-sidebar"
import AppSidebarNav from "@/components/common/app-sidebar-nav"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          <AppSidebar collapsible="dock" />
          <SidebarInset className="max-h-svh overflow-hidden">
            <AppSidebarNav />
            <div className="overflow-y-scroll p-2 md:p-4">{children}</div>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  )
}
